CREATE TABLE [dbo].[BUILD_INFO] (
    [BUILD_INFO_ID] UNIQUEIDENTIFIER CONSTRAINT [DF_BUILD_INFO_BUILD_INFO_ID] DEFAULT (newsequentialid()) NOT NULL, 
    [BUILD_INFO_TYPE] UNIQUEIDENTIFIER NOT NULL, 
    CONSTRAINT [PK_BUILD_INFO] PRIMARY KEY ([BUILD_INFO_ID])
);

